apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-propia
  labels:
    app: app-propia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-propia
  template:
    metadata:
      labels:
        app: app-propia
    spec:
      containers:
        - name: app-propia
          image: app-propia:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-propia
spec:
  type: NodePort
  selector:
    app: app-propia
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
